from __future__ import annotations

from typing import Optional


ERROR_OK = "OK"
ERROR_UNKNOWN = "UNKNOWN"

ERROR_PROMPT_CONTRACT_MISSING_FIELD = "PROMPT_CONTRACT_MISSING_FIELD"
ERROR_PROMPT_CONTRACT_INVALID_OUTPUT = "PROMPT_CONTRACT_INVALID_OUTPUT"
ERROR_PROLOG_CONTRACT_INVALID = "PROLOG_CONTRACT_INVALID"
ERROR_SWIPL_TIMEOUT = "SWIPL_TIMEOUT"
ERROR_SWIPL_CALL_FAILED = "SWIPL_CALL_FAILED"
ERROR_SCHEMA_INVALID_JSON = "SCHEMA_INVALID_JSON"
ERROR_LEGACY_SCHEMA = "LEGACY_SCHEMA"


KNOWN_ERROR_CODES = {
    ERROR_OK,
    ERROR_UNKNOWN,
    ERROR_PROMPT_CONTRACT_MISSING_FIELD,
    ERROR_PROMPT_CONTRACT_INVALID_OUTPUT,
    ERROR_PROLOG_CONTRACT_INVALID,
    ERROR_SWIPL_TIMEOUT,
    ERROR_SWIPL_CALL_FAILED,
    ERROR_SCHEMA_INVALID_JSON,
    ERROR_LEGACY_SCHEMA,
}


def normalize_error_code(error_code: Optional[str], default: str = ERROR_UNKNOWN) -> str:
    if not error_code:
        return default
    normalized = str(error_code).strip().upper()
    return normalized or default